name: E2E on Chrome

on: push

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          headless: true
          start: npm run dev
          wait-on: http://localhost:3000

